#! /usr/bin/env bash

set -e # prevent any kind of script failures

source script/env "$@"

KEEP_UP=false

# check for the --keep flag
# if it exists, we will keep the docker processes up after the tests run
for arg in "$@"; do
  if [ "$arg" == "--keep" ]; then
    KEEP_UP=true
    break
  fi
done

# check to ensure docker is running
if ! docker info &> /dev/null; then
  echo -e "${RED}Docker is not running. Please start Docker and try again.${OFF}"
  exit 1
fi

echo -e "${PURPLE}[#]${OFF} ${BLUE}Killing old docker processes${OFF}"
docker compose down --remove-orphans -v -t 1
docker network prune --force
docker compose up --build -d

# Conditionally output verbose information about the Docker environment if CI is set
if [ "$CI" == "true" ]; then
  echo -e "${PURPLE}[#]${OFF} ${BLUE}Docker version${OFF}"
  docker version

  echo -e "${PURPLE}[#]${OFF} ${BLUE}Docker Compose version${OFF}"
  docker compose version

  echo -e "${PURPLE}[#]${OFF} ${BLUE}Docker info${OFF}"
  docker info

  echo -e "${PURPLE}[#]${OFF} ${BLUE}Docker Compose ps${OFF}"
  docker compose ps

  echo -e "${PURPLE}[#]${OFF} ${BLUE}Docker Compose logs${OFF}"
  docker compose logs

  echo -e "${PURPLE}[#]${OFF} ${BLUE}Docker container stats${OFF}"
  docker stats --no-stream

  echo -e "${PURPLE}[#]${OFF} ${BLUE}Docker container inspect${OFF}"
  docker inspect server

  echo -e "${PURPLE}[#]${OFF} ${BLUE}Docker container logs${OFF}"
  docker compose logs server
fi

echo -e "${PURPLE}[#]${OFF} ${BLUE}Running acceptance tests${OFF}"
bundle exec rspec spec/acceptance/acceptance_tests.rb

if [ "$KEEP_UP" == "false" ]; then
  echo -e "${PURPLE}[#]${OFF} ${BLUE}Stopping docker processes${OFF}"
  docker compose down --remove-orphans -v -t 1
  docker network prune --force
else
  echo -e "${PURPLE}[#]${OFF} ${BLUE}Keeping docker processes up${OFF}"
fi

echo -e "${PURPLE}[#]${OFF} ${GREEN}Acceptance tests passed${OFF}"
