#! /usr/bin/env bash

set -e

source script/env "$@"

GEM_NAME=$(ls | grep gemspec | cut -d. -f1)
GEM_VERSION=$(gem build $GEM_NAME.gemspec 2>&1 | grep Version | cut -d':' -f 2 | tr -d " \t\n\r")

echo "built $GEM_NAME $GEM_VERSION"
