name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - lib/net/http/version.rb

permissions: {}

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      packages: write
      attestations: write
    uses: github/salsa/.github/workflows/ruby.yml@main
    with:
      bootstrap_script: script/bootstrap
      build_script: script/build
    secrets:
      RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
